index:
  timeout: 10
  cells:
    ubuntu:
      menu:
        class: os
        label: "Select preseeds for ubuntu installer..."
        submenu:
          automatic:
            label: "Automatic, default(raid1)"
            params:
              raid: raid1
            args:
              kernel_params: console=tty0 console=ttyS1,115200n8 DEBCONF_DEBUG=5
          manual:
            label: "Manual install"
            params:
              manual: true
            args:
              kernel_params: console=tty0 console=ttyS1,115200n8 DEBCONF_DEBUG=5
      args:
        user:
          name: console
          hash: HASH
          keys:
            - foo
        preseed:
          swapsize: 4000
          storagefs: ext4
    alchemy:
      menu:
        class: util
        label: "Boot Alchemy Linux"
      args:
        kernel_params: net real_init=/sbin/init
    memtest:
      menu:
        class: util
        label:   "Run Memtest86"
      args:
        kernel_params: console=tty0 console=ttyS1,115200n8
        passes: 5
