index:
  timeout: 10
  cells:
    ubuntu:
      menu:
        class: os
        label: "Select preseeds for ubuntu installer..."
        submenu:
          automatic:
            label: "Automatic, default(raid1)"
            params:
              raid: raid1
            args:
              kernel_params: console=tty0 console=ttyS1,115200n8 DEBCONF_DEBUG=5
          automatic-raid5:
            label: "Automatic, raid5 (6 disks)"
            params:
              raid: raid5
            args:
              kernel_params: console=tty0 console=ttyS1,115200n8 DEBCONF_DEBUG=5
          automatic-single-sda:
            label: "Automatic, single disk - sda"
            params:
              raid: single
              root_disk: sda
            args:
              kernel_params: console=tty0 console=ttyS1,115200n8 DEBCONF_DEBUG=5
          automatic-single-sdb:
            label: "Automatic, single disk - sdb"
            params:
              raid: single
              root_disk: sdb
            args:
              kernel_params: console=tty0 console=ttyS1,115200n8 DEBCONF_DEBUG=5
          manual:
            label: "Manual install"
            params:
              manual: true
            args:
              kernel_params: console=tty0 console=ttyS1,115200n8 DEBCONF_DEBUG=5
      args:
        user:
          name: console
          hash: "$6$7EYCq7Ft$FOPhIAY4EdVKXenxnt6zeyuSw1WANAz7UehTnCVsH3wP8m8S7qAavFn7j7ef6oVcqyrY0GcnllVJXeuB3MnQS."
          keys:
            - foo
        preseed:
          swapsize: 4000
          storagefs: ext4
    alchemy:
      menu:
        class: util
        label: "Boot Alchemy Linux"
      args:
        kernel_params: net real_init=/sbin/init
    memtest:
      menu:
        class: util
        label:   "Run Memtest86"
      args:
        kernel_params: console=tty0 console=ttyS1,115200n8
        passes: 5
